---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-8.7
  run_list:
  - recipe[apt]

suites:
- name: gruyere
  run_list:
  - recipe[gruyere]
- name: with-proxy
  run_list:
  - recipe[gruyere::apache2_proxy]
